[package]
name = "gust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
inquire = "0.2.1"
linked-hash-map = "0.5.6"
